import type {
    JSONValue,
    LanguageModelV3FinishReason,
    LanguageModelV3StreamPart,
    LanguageModelV3Usage,
} from "@ai-sdk/provider";
import type { AgentMessageDeltaNotification } from "@dascowork/codex-app-server-client/protocol/app-server-protocol/v2/AgentMessageDeltaNotification";
import type { FileChangePatchUpdatedNotification } from "@dascowork/codex-app-server-client/protocol/app-server-protocol/v2/FileChangePatchUpdatedNotification";
import type { ItemCompletedNotification } from "@dascowork/codex-app-server-client/protocol/app-server-protocol/v2/ItemCompletedNotification";
import type { ItemGuardianApprovalReviewCompletedNotification } from "@dascowork/codex-app-server-client/protocol/app-server-protocol/v2/ItemGuardianApprovalReviewCompletedNotification";
import type { ItemGuardianApprovalReviewStartedNotification } from "@dascowork/codex-app-server-client/protocol/app-server-protocol/v2/ItemGuardianApprovalReviewStartedNotification";
import type { ItemStartedNotification } from "@dascowork/codex-app-server-client/protocol/app-server-protocol/v2/ItemStartedNotification";
import type { McpToolCallProgressNotification } from "@dascowork/codex-app-server-client/protocol/app-server-protocol/v2/McpToolCallProgressNotification";
import type { ReasoningSummaryPartAddedNotification } from "@dascowork/codex-app-server-client/protocol/app-server-protocol/v2/ReasoningSummaryPartAddedNotification";
import type { ThreadTokenUsageUpdatedNotification } from "@dascowork/codex-app-server-client/protocol/app-server-protocol/v2/ThreadTokenUsageUpdatedNotification";
import type { TurnCompletedNotification } from "@dascowork/codex-app-server-client/protocol/app-server-protocol/v2/TurnCompletedNotification";
import type { TurnDiffUpdatedNotification } from "@dascowork/codex-app-server-client/protocol/app-server-protocol/v2/TurnDiffUpdatedNotification";
import type { TurnPlanUpdatedNotification } from "@dascowork/codex-app-server-client/protocol/app-server-protocol/v2/TurnPlanUpdatedNotification";
import type { TurnStartedNotification } from "@dascowork/codex-app-server-client/protocol/app-server-protocol/v2/TurnStartedNotification";
import type { TurnStatus } from "@dascowork/codex-app-server-client/protocol/app-server-protocol/v2/TurnStatus";

import { turnErrorMessage } from "../turn-error";
import { stripUndefined } from "../utils/object";
import { withProviderMetadata } from "./provider-metadata";
import {
    type CodexRenderableThreadItem,
    type CodexThreadItemToolInvocation,
    stringifyToolInput,
    toolInvocationForItem,
    webSearchHasContent,
} from "./shared-item-extractors";
import {
    type FileChangeDiffBatch,
    fileChangeDiffBatchesForOrderedItems,
    type TurnDiffItem,
    turnDiffItem,
} from "./turn-diff";
import type { CodexDynamicToolCallItem } from "./types";

export interface CodexEventMapperInput {
    method: string
    params?: unknown
}

/** Shared shape for reasoning/plan/fileChange delta params. */
interface DeltaParams {
    itemId?: string
    delta?: string
}

type DynamicToolCallItem = CodexDynamicToolCallItem;
type CodexThreadItemToolStart = Pick<
    CodexThreadItemToolInvocation,
  "toolCallId" | "toolName" | "input"
>;
type AgentMessagePhase = NonNullable<
    Extract<CodexRenderableThreadItem, { type: "agentMessage" }>["phase"]
>;
/**
 * Minimal protocol state required to merge a `thread/resume` active-turn
 * snapshot into a stream that already delivered some notifications.  This is
 * deliberately item based: UI message ids are generated by AI SDK downstream
 * and cannot safely be used as an app-server recovery cursor.
 */
export type CodexExistingTurnRecoveryState = {
    turnId?: string
    textByItemId: Record<string, string>
    emittedProviderToolCallIds: string[]
    completedProviderToolCallIds: string[]
};
type AutoApprovalReviewItem = Record<string, unknown> & {
    id: string
    type: "automaticApprovalReview"
    status: "inProgress" | "completed"
    outcome: string | null
    startedAtMs: number
    completedAtMs?: number
    targetItemId: string | null
    review: ItemGuardianApprovalReviewStartedNotification["review"]
    action: ItemGuardianApprovalReviewStartedNotification["action"]
    decisionSource?: ItemGuardianApprovalReviewCompletedNotification["decisionSource"]
};

type AutoApprovalReviewNotification =
  | ItemGuardianApprovalReviewStartedNotification
  | ItemGuardianApprovalReviewCompletedNotification;

const EMPTY_USAGE: LanguageModelV3Usage = {
    inputTokens: {
        total: undefined,
        noCache: undefined,
        cacheRead: undefined,
        cacheWrite: undefined,
    },
    outputTokens: {
        total: undefined,
        text: undefined,
        reasoning: undefined,
    },
};

function toFinishReason(status: TurnStatus | undefined): LanguageModelV3FinishReason
{
    switch (status)
    {
        case "completed":
            return { unified: "stop", raw: "completed" };
        case "failed":
            return { unified: "error", raw: "failed" };
        case "interrupted":
            return { unified: "other", raw: "interrupted" };
        default:
            return { unified: "other", raw: undefined };
    }
}

function autoApprovalReviewItem(
    notification: AutoApprovalReviewNotification,
    status: AutoApprovalReviewItem["status"],
): AutoApprovalReviewItem
{
    return stripUndefined({
        id: notification.reviewId,
        type: "automaticApprovalReview" as const,
        status,
        outcome: notification.review.status,
        startedAtMs: notification.startedAtMs,
        completedAtMs: "completedAtMs" in notification ? notification.completedAtMs : undefined,
        targetItemId: notification.targetItemId,
        review: notification.review,
        action: notification.action,
        decisionSource: "decisionSource" in notification ? notification.decisionSource : undefined,
    });
}

function autoApprovalReviewInvocation(item: AutoApprovalReviewItem): CodexThreadItemToolStart & {
    result: { item: AutoApprovalReviewItem }
}
{
    return {
        toolCallId: item.id,
        toolName: "codex_automatic_approval_review",
        input: stripUndefined({
            targetItemId: item.targetItemId,
            review: item.review,
            action: item.action,
            startedAtMs: item.startedAtMs,
            completedAtMs: item.completedAtMs,
            decisionSource: item.decisionSource,
        }),
        result: { item },
    };
}

function asToolResult(value: unknown): NonNullable<JSONValue>
{
    return value as NonNullable<JSONValue>;
}

/**
 * A completed command can still represent a failed tool invocation: shell
 * processes use a non-zero exit code for that outcome while retaining the
 * protocol status `completed`. Preserve that distinction for AI SDK consumers
 * so a failed tool record is not rendered as a successful one.
 */
function toolInvocationFailed(item: CodexRenderableThreadItem): boolean
{
    switch (item.type)
    {
        case "commandExecution":
            return (
                item.status === "failed" ||
        item.status === "declined" ||
        (typeof item.exitCode === "number" && item.exitCode !== 0)
            );
        case "dynamicToolCall":
            return item.status === "failed" || item.success === false;
        case "mcpToolCall":
            return item.status === "failed" || item.error !== null;
        default:
            return false;
    }
}

function normalizePlanStatus(status: string): string
{
    if (status === "in_progress")
    {
        return "inProgress";
    }
    return status;
}

function todoListItemForPlanUpdate(
    notification: TurnPlanUpdatedNotification,
    itemId: string,
): Record<string, unknown>
{
    return stripUndefined({
        id: itemId,
        type: "todoList",
        status: "inProgress",
        explanation: notification.explanation ?? undefined,
        items: notification.plan.map((step) => ({
            label: step.step,
            status: normalizePlanStatus(step.status),
        })),
    });
}

function turnDiffItemForNotification(
    notification: TurnDiffUpdatedNotification,
    itemId: string,
    status: TurnDiffItem["status"],
    cwd?: string,
): Record<string, unknown>
{
    return {
        ...turnDiffItem({
            id: itemId,
            threadId: notification.threadId,
            status,
            cwd,
            diff: notification.diff,
        }),
    };
}

type TurnDiffState = {
    toolCallId: string
    cwd?: string | undefined
    diff: string
};

type FileChangePatchState = {
    cwd?: string | undefined
    changes: Extract<CodexRenderableThreadItem, { type: "fileChange" }>["changes"]
};

function turnItemKey(turnId: string, itemId: string): string
{
    return `${turnId}\0${itemId}`;
}

function sourceItemIdForPart(part: LanguageModelV3StreamPart): string | undefined
{
    switch (part.type)
    {
        case "text-start":
        case "text-delta":
        case "text-end":
        case "reasoning-start":
        case "reasoning-delta":
        case "reasoning-end":
        case "tool-input-start":
        case "tool-input-delta":
        case "tool-input-end":
            return part.id;
        case "tool-call":
        case "tool-result":
            return part.toolCallId;
        default:
            return undefined;
    }
}

export interface CodexEventMapperOptions {
    /** Emit plan updates as tool-call/tool-result parts. Default: true. */
    emitPlanUpdates?: boolean
}

/**
 * Extract threadId from notification params. All codex protocol notifications
 * include threadId as a top-level field. Returns undefined for notifications
 * that don't carry a threadId (e.g. codex/event/* wrappers, account events).
 */
export function extractNotificationThreadId(params: unknown): string | undefined
{
    if (params && typeof params === "object" && "threadId" in params)
    {
        const val = (params as Record<string, unknown>)["threadId"];
        return typeof val === "string" ? val : undefined;
    }
    return undefined;
}

// No-op handler for intentionally ignored events.
const NOOP = (): LanguageModelV3StreamPart[] => [];
export class CodexEventMapper
{
    private readonly options: Required<CodexEventMapperOptions>;
    private streamStarted = false;
    private readonly openTextParts = new Set<string>();
    private readonly textByItemId = new Map<string, string>();
    private readonly agentMessagePhaseByItemId = new Map<string, AgentMessagePhase>();
    private readonly openReasoningParts = new Set<string>();
    private readonly openToolCalls = new Map<
        string,
        { toolName: string; item?: Record<string, unknown> }
    >();
    /**
   * Completed provider items are terminal protocol state.  Keeping that state
   * for this mapper instance prevents a replayed item/started or
   * item/completed notification from reopening an already-rendered tool call.
   * This is item lifecycle tracking, not a cross-owner UI deduplication layer.
   */
    private readonly completedProviderToolCallIds = new Set<string>();
    private readonly emittedProviderToolCallIds = new Set<string>();
    /**
   * Item IDs for dynamicToolCall items seen in cross-call mode — tracked so
   * item/tool/call dedup fires without adding them to openToolCalls (which
   * would cause handleTurnCompleted to emit spurious error tool-results).
    */
    private readonly _sdkDynamicToolCallIds = new Set<string>();
    private readonly turnDiffByTurnId = new Map<string, TurnDiffState>();
    private readonly currentCwdByTurnId = new Map<string, string>();
    private readonly fileChangePatchByItemKey = new Map<string, FileChangePatchState>();
    private readonly fileChangeBatchesByTurnId = new Map<string, FileChangeDiffBatch[]>();
    /**
   * Set to true by enableCrossCallMode() when PersistentTransport + SDK tools
   * are active. In cross-call mode the mapper stays silent for dynamicToolCall
   * items; the cross-call handler in model.ts owns emission.
   */
    private _crossCallMode = false;
    private readonly planSequenceByTurnId = new Map<string, number>();
    private threadId: string | undefined;
    private turnId: string | undefined;
    private threadPath: string | undefined;
    private threadCwd: string | undefined;
    private latestUsage: LanguageModelV3Usage | undefined;

    private readonly handlers: Record<string, (params: unknown) => LanguageModelV3StreamPart[]>;

    constructor(options?: CodexEventMapperOptions)
    {
        this.options = {
            emitPlanUpdates: options?.emitPlanUpdates ?? true,
        };

        this.handlers = {
            "turn/started": (p) => this.handleTurnStarted(p),
            "item/started": (p) => this.handleItemStarted(p),
            "item/agentMessage/delta": (p) => this.handleAgentMessageDelta(p),
            "item/completed": (p) => this.handleItemCompleted(p),
            "item/autoApprovalReview/started": (p) => this.handleAutoApprovalReviewStarted(p),
            "item/autoApprovalReview/completed": (p) => this.handleAutoApprovalReviewCompleted(p),
            "item/reasoning/textDelta": (p) => this.handleReasoningDelta(p),
            "item/reasoning/summaryTextDelta": (p) => this.handleReasoningDelta(p),
            "item/plan/delta": (p) => this.handleReasoningDelta(p),
            "item/reasoning/summaryPartAdded": (p) => this.handleSummaryPartAdded(p),
            "turn/plan/updated": (p) => this.handlePlanUpdated(p),
            "turn/diff/updated": (p) => this.handleTurnDiffUpdated(p),
            "item/fileChange/patchUpdated": (p) => this.handleFileChangePatchUpdated(p),
            "item/mcpToolCall/progress": (p) => this.handleMcpToolCallProgress(p),
            "item/tool/callStarted": (p) => this.handleToolCallStarted(p),
            "item/tool/callDelta": (p) => this.handleToolCallDelta(p),
            "item/tool/callFinished": (p) => this.handleToolCallFinished(p),
            "item/tool/call": (p) => this.handleToolCall(p),
            "thread/tokenUsage/updated": (p) => this.handleTokenUsageUpdated(p),
            "turn/completed": (p) => this.handleTurnCompleted(p),

            // Intentionally ignored: wrapper/duplicate events handled by their canonical forms above.
            "codex/event/agent_reasoning": NOOP,
            "codex/event/agent_reasoning_section_break": NOOP,
            "codex/event/plan_update": NOOP,
            // Intentionally ignored: web search and MCP wrappers mirror item events.
            "codex/event/web_search_begin": NOOP,
            "codex/event/web_search_end": NOOP,
            "codex/event/mcp_tool_call_begin": NOOP,
            "codex/event/mcp_tool_call_end": NOOP,

            // Intentionally ignored: streaming output deltas — the full output arrives
            // in item/completed (aggregatedOutput), making these redundant.
            "item/commandExecution/outputDelta": NOOP,
            "item/fileChange/outputDelta": NOOP,

            "codex/event/turn_diff": NOOP,
        };
    }

    /**
   * Switches the mapper into cross-call mode. Call this when PersistentTransport
   * and SDK tools are both active so the cross-call handler in model.ts owns
   * dynamicToolCall emission instead of the mapper.
   */
    enableCrossCallMode(): void
    {
        this._crossCallMode = true;
    }

    setThreadId(threadId: string): void
    {
        this.threadId = threadId;
    }

    setThreadPath(threadPath: string | null | undefined): void
    {
        this.threadPath = threadPath ?? undefined;
    }

    setThreadCwd(threadCwd: string | null | undefined): void
    {
        this.threadCwd = threadCwd ?? undefined;
    }

    setTurnId(turnId: string): void
    {
        this.turnId = turnId;
    }

    getTurnId(): string | undefined
    {
        return this.turnId;
    }

    /** Captures state at a transport boundary without exposing mapper internals. */
    snapshotExistingTurnRecoveryState(): CodexExistingTurnRecoveryState
    {
        return {
            ...(this.turnId ? { turnId: this.turnId } : {}),
            textByItemId: Object.fromEntries(this.textByItemId),
            emittedProviderToolCallIds: [...this.emittedProviderToolCallIds],
            completedProviderToolCallIds: [...this.completedProviderToolCallIds],
        };
    }

    /** Seeds a fresh mapper before it replays a running thread snapshot. */
    restoreExistingTurnRecoveryState(state: CodexExistingTurnRecoveryState | undefined): void
    {
        if (!state)
        {
            return;
        }
        if (state.turnId)
        {
            this.turnId = state.turnId;
        }
        for (const [itemId, text] of Object.entries(state.textByItemId))
        {
            this.textByItemId.set(itemId, text);
            // The original stream already opened this UI text part. A later live
            // delta from the new transport must continue it rather than restart it.
            this.openTextParts.add(itemId);
        }
        for (const itemId of state.emittedProviderToolCallIds)
        {
            this.emittedProviderToolCallIds.add(itemId);
        }
        for (const itemId of state.completedProviderToolCallIds)
        {
            this.completedProviderToolCallIds.add(itemId);
        }
    }

    /**
   * Rehydrates the visible, in-progress portion of a resumed turn.  Text is
   * emitted only when the app-server snapshot extends the already-delivered
   * prefix.  We intentionally do not synthesize `text-end`: the turn is
   * still active and a later item/completed notification remains canonical.
   */
    mapExistingTurnSnapshot(turn: {
        id: string
        items: readonly CodexRenderableThreadItem[]
    }): LanguageModelV3StreamPart[]
    {
        this.turnId = turn.id;
        const parts = this.map({ method: "turn/started", params: { turn: { id: turn.id } } });
        for (const item of turn.items)
        {
            if (item.type === "agentMessage")
            {
                this.recordAgentMessagePhase(item);
                const delivered = this.textByItemId.get(item.id) ?? "";
                const text = item.text ?? "";
                if (!text.startsWith(delivered))
                {
                    // A non-prefix snapshot cannot be merged without risking
                    // duplicated or corrupted text. Wait for canonical live
                    // notifications instead of guessing.
                    continue;
                }
                const suffix = text.slice(delivered.length);
                if (!suffix)
                {
                    continue;
                }
                parts.push(
                    ...this.map({
                        method: "item/agentMessage/delta",
                        params: { itemId: item.id, delta: suffix },
                    }),
                );
                continue;
            }
            parts.push(...this.map({ method: "item/started", params: { item } }));
            // Snapshot items are materialized protocol items. For provider tool
            // calls, replay completion after start so an already-emitted call
            // can receive exactly one late result. Other types are finalized by
            // their normal live notifications.
            if (toolInvocationForItem(item))
            {
                parts.push(...this.map({ method: "item/completed", params: { item } }));
            }
        }
        return parts;
    }

    map(event: CodexEventMapperInput): LanguageModelV3StreamPart[]
    {
        const handler = this.handlers[event.method];
        return handler ? handler(event.params) : [];
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    private withMeta<T extends LanguageModelV3StreamPart>(
        part: T,
        extra?: Record<string, unknown>,
    ): T
    {
        const sourceItemId = sourceItemIdForPart(part);
        const metadata = {
            ...(sourceItemId ? { sourceItemId } : {}),
            ...(extra ?? {}),
        };

        if (part.type === "stream-start")
        {
            return withProviderMetadata(part, this.threadId, this.turnId, this.threadPath, metadata);
        }

        return withProviderMetadata(part, this.threadId, this.turnId, undefined, metadata);
    }

    private ensureStreamStarted(parts: LanguageModelV3StreamPart[]): void
    {
        if (!this.streamStarted)
        {
            parts.push(this.withMeta({ type: "stream-start", warnings: [] }));
            this.streamStarted = true;
        }
    }

    private emitReasoningDelta(parts: LanguageModelV3StreamPart[], id: string, delta: string): void
    {
        this.ensureStreamStarted(parts);

        if (!this.openReasoningParts.has(id))
        {
            this.openReasoningParts.add(id);
            parts.push(this.withMeta({ type: "reasoning-start", id }));
        }

        if (delta)
        {
            parts.push(this.withMeta({ type: "reasoning-delta", id, delta }));
        }
    }

    private nextPlanSequence(turnId: string): number
    {
        const next = (this.planSequenceByTurnId.get(turnId) ?? 0) + 1;
        this.planSequenceByTurnId.set(turnId, next);
        return next;
    }

    private recordAgentMessagePhase(
        item: Extract<CodexRenderableThreadItem, { type: "agentMessage" }>,
    ): void
    {
        if (item.phase)
        {
            this.agentMessagePhaseByItemId.set(item.id, item.phase);
        }
    }

    private agentMessageMetadata(itemId: string): Record<string, string> | undefined
    {
        const messagePhase = this.agentMessagePhaseByItemId.get(itemId);
        return messagePhase ? { messagePhase } : undefined;
    }

    // ── Handlers ─────────────────────────────────────────────────────────────

    // turn/started
    private handleTurnStarted(params: unknown): LanguageModelV3StreamPart[]
    {
        const p = params as TurnStartedNotification | undefined;
        if (p?.turn?.id)
        {
            this.turnId = p.turn.id;
        }
        const parts: LanguageModelV3StreamPart[] = [];
        this.ensureStreamStarted(parts);
        return parts;
    }

    // item/started
    private handleItemStarted(params: unknown): LanguageModelV3StreamPart[]
    {
        const p = (params ?? {}) as ItemStartedNotification;
        const item = p.item as CodexRenderableThreadItem | undefined;
        if (!item?.id)
        {
            return [];
        }

        if (p.turnId && item.type === "commandExecution" && item.cwd)
        {
            this.currentCwdByTurnId.set(p.turnId, item.cwd);
        }
        if (p.turnId && item.type === "fileChange")
        {
            this.fileChangePatchByItemKey.set(turnItemKey(p.turnId, item.id), {
                cwd: this.currentCwdByTurnId.get(p.turnId) ?? this.threadCwd,
                changes: item.changes,
            });
        }

        const parts: LanguageModelV3StreamPart[] = [];

        switch (item.type)
        {
            case "agentMessage": {
                this.recordAgentMessagePhase(item);
                this.ensureStreamStarted(parts);
                this.openTextParts.add(item.id);
                parts.push(
                    this.withMeta({ type: "text-start", id: item.id }, this.agentMessageMetadata(item.id)),
                );
                break;
            }
            case "commandExecution": {
                this.startProviderToolCall(parts, item);
                break;
            }
            case "dynamicToolCall": {
                if (this._crossCallMode)
                {
                    // Cross-call mode: suppress mapper emission. The cross-call handler
                    // in model.ts emits the definitive (non-providerExecuted) tool-call
                    // from the JSON-RPC request. Track the ID so item/tool/call dedup
                    // fires without adding it to openToolCalls (which would cause
                    // handleTurnCompleted to emit a spurious error tool-result).
                    this.ensureStreamStarted(parts);
                    this._sdkDynamicToolCallIds.add(item.id);
                    break;
                }

                // Non-cross-call mode: emit providerExecuted tool-call so telemetry
                // is preserved. item/completed will emit the tool-result.
                this.startProviderToolCall(parts, item);
                break;
            }
            case "fileChange":
            case "mcpToolCall":
            case "sleep":
            case "collabAgentToolCall":
            case "collabToolCall":
            case "imageView":
            case "contextCompaction":
            case "enteredReviewMode":
            case "exitedReviewMode":
            case "hookPrompt":
            case "subAgentActivity":
            case "loadedTool":
            case "loaded-tool":
                this.startProviderToolCall(parts, item, {
                    emitPreliminaryItem: item.type === "mcpToolCall" || item.type === "sleep",
                });
                break;
            case "webSearch":
                this.ensureStreamStarted(parts);
                // Codex usually emits webSearch item/started as an empty placeholder
                // and fills query/action at item/completed. The shared extractor
                // suppresses placeholders here and handleItemCompleted emits the
                // complete call/result pair once content exists.
                this.startProviderToolCall(parts, item);
                break;
            case "reasoning":
            case "plan": {
                this.emitReasoningDelta(parts, item.id, "");
                break;
            }
            default:
                break;
        }

        return parts;
    }

    // item/agentMessage/delta
    private handleAgentMessageDelta(params: unknown): LanguageModelV3StreamPart[]
    {
        const delta = (params ?? {}) as AgentMessageDeltaNotification;
        if (!delta.itemId || !delta.delta)
        {
            return [];
        }

        const parts: LanguageModelV3StreamPart[] = [];
        this.ensureStreamStarted(parts);

        if (!this.openTextParts.has(delta.itemId))
        {
            this.openTextParts.add(delta.itemId);
            parts.push(
                this.withMeta(
                    { type: "text-start", id: delta.itemId },
                    this.agentMessageMetadata(delta.itemId),
                ),
            );
        }

        parts.push(
            this.withMeta(
                { type: "text-delta", id: delta.itemId, delta: delta.delta },
                this.agentMessageMetadata(delta.itemId),
            ),
        );
        this.textByItemId.set(
            delta.itemId,
            `${this.textByItemId.get(delta.itemId) ?? ""}${delta.delta}`,
        );
        return parts;
    }

    // item/completed
    private handleItemCompleted(params: unknown): LanguageModelV3StreamPart[]
    {
        const p = (params ?? {}) as ItemCompletedNotification;
        const item = p.item as CodexRenderableThreadItem | undefined;
        if (!item?.id)
        {
            return [];
        }

        if (p.turnId && item.type === "commandExecution" && item.cwd)
        {
            this.currentCwdByTurnId.set(p.turnId, item.cwd);
        }
        if (p.turnId && item.type === "fileChange")
        {
            const key = turnItemKey(p.turnId, item.id);
            const tracked = this.fileChangePatchByItemKey.get(key);
            const changes = tracked?.changes ?? item.changes;
            if (
                item.status !== "failed" &&
        item.status !== "declined" &&
        changes.length > 0
            )
            {
                const batches = this.fileChangeBatchesByTurnId.get(p.turnId) ?? [];
                batches.push({ cwd: tracked?.cwd ?? this.currentCwdByTurnId.get(p.turnId) ?? this.threadCwd, changes });
                this.fileChangeBatchesByTurnId.set(p.turnId, batches);
            }
            this.fileChangePatchByItemKey.delete(key);
        }

        const parts: LanguageModelV3StreamPart[] = [];

        if (item.type === "agentMessage")
        {
            this.recordAgentMessagePhase(item);
            const metadata = this.agentMessageMetadata(item.id);

            const deliveredText = this.textByItemId.get(item.id) ?? "";
            const completionText = item.text ?? "";
            if (completionText && completionText.startsWith(deliveredText))
            {
                const suffix = completionText.slice(deliveredText.length);
                if (suffix)
                {
                    this.ensureStreamStarted(parts);
                    if (!this.openTextParts.has(item.id))
                    {
                        this.openTextParts.add(item.id);
                        parts.push(this.withMeta({ type: "text-start", id: item.id }, metadata));
                    }

                    parts.push(this.withMeta({ type: "text-delta", id: item.id, delta: suffix }, metadata));
                    this.textByItemId.set(item.id, completionText);
                }
            }

            if (this.openTextParts.has(item.id))
            {
                parts.push(this.withMeta({ type: "text-end", id: item.id }, metadata));
                this.openTextParts.delete(item.id);
            }
            this.agentMessagePhaseByItemId.delete(item.id);
        }
        else if (this.openToolCalls.has(item.id))
        {
            const tracked = this.openToolCalls.get(item.id)!;
            const invocation = toolInvocationForItem(item);
            if (!invocation)
            {
                return parts;
            }

            // A replayed completion (adopted from a previous step) can be the
            // first part of this stream — make sure stream-start precedes it.
            this.ensureStreamStarted(parts);

            parts.push(
                this.withMeta({
                    type: "tool-result",
                    toolCallId: item.id,
                    toolName: tracked.toolName,
                    result: invocation.result,
                    ...(toolInvocationFailed(item) ? { isError: true } : {}),
                }),
            );

            this.openToolCalls.delete(item.id);
            this.completedProviderToolCallIds.add(item.id);
        }
        else if (
            item.type === "webSearch" &&
      !this.completedProviderToolCallIds.has(item.id) &&
      webSearchHasContent(item.query, item.action)
        )
        {
            // webSearch item/started was a contentless placeholder suppressed in
            // handleItemStarted; the real query/action arrive here. Emit the full
            // provider-executed call + result now (the search ran to completion).
            this.ensureStreamStarted(parts);
            const invocation = toolInvocationForItem(item);
            if (!invocation)
            {
                return parts;
            }
            parts.push(
                this.withMeta({
                    type: "tool-call",
                    toolCallId: invocation.toolCallId,
                    toolName: invocation.toolName,
                    input: stringifyToolInput(invocation.input),
                    providerExecuted: true,
                    dynamic: true,
                }),
            );
            parts.push(
                this.withMeta({
                    type: "tool-result",
                    toolCallId: invocation.toolCallId,
                    toolName: invocation.toolName,
                    result: invocation.result,
                }),
            );
            this.completedProviderToolCallIds.add(item.id);
        }
        else if (this.openReasoningParts.has(item.id))
        {
            parts.push(this.withMeta({ type: "reasoning-end", id: item.id }));
            this.openReasoningParts.delete(item.id);
        }
        else if (item.type === "imageGeneration" && item.result)
        {
            this.ensureStreamStarted(parts);

            const extra = {
                ...(item.revisedPrompt && { revisedPrompt: item.revisedPrompt }),
                ...(item.savedPath && { savedPath: item.savedPath }),
            };

            parts.push(
                this.withMeta(
                    { type: "file" as const, mediaType: "image/png", data: item.result },
                    {
                        sourceItemId: item.id,
                        ...extra,
                    },
                ),
            );
        }

        return parts;
    }

    // item/reasoning/textDelta, item/reasoning/summaryTextDelta, item/plan/delta
    private handleReasoningDelta(params: unknown): LanguageModelV3StreamPart[]
    {
        const delta = (params ?? {}) as DeltaParams;
        if (!delta.itemId || !delta.delta)
        {
            return [];
        }
        const parts: LanguageModelV3StreamPart[] = [];
        this.emitReasoningDelta(parts, delta.itemId, delta.delta);
        return parts;
    }

    // item/reasoning/summaryPartAdded
    private handleSummaryPartAdded(params: unknown): LanguageModelV3StreamPart[]
    {
        const p = (params ?? {}) as ReasoningSummaryPartAddedNotification;
        if (!p.itemId)
        {
            return [];
        }
        const parts: LanguageModelV3StreamPart[] = [];
        this.emitReasoningDelta(parts, p.itemId, "\n\n");
        return parts;
    }

    // turn/plan/updated
    private handlePlanUpdated(params: unknown): LanguageModelV3StreamPart[]
    {
        if (!this.options.emitPlanUpdates)
        {
            return [];
        }

        const p = (params ?? {}) as TurnPlanUpdatedNotification;
        const turnId = p.turnId;
        const plan = p.plan;
        if (!turnId || !plan)
        {
            return [];
        }

        const parts: LanguageModelV3StreamPart[] = [];
        this.ensureStreamStarted(parts);
        const planSequence = this.nextPlanSequence(turnId);
        const toolCallId = `plan:${turnId}:${planSequence}`;
        const toolName = "codex_todo_list";
        const item = todoListItemForPlanUpdate(p, toolCallId);

        parts.push(
            this.withMeta({
                type: "tool-call",
                toolCallId,
                toolName,
                input: JSON.stringify({ explanation: p.explanation ?? undefined }),
                providerExecuted: true,
                dynamic: true,
            }),
        );

        parts.push(
            this.withMeta({
                type: "tool-result",
                toolCallId,
                toolName,
                result: asToolResult({ item }),
            }),
        );

        return parts;
    }

    // turn/diff/updated
    private handleTurnDiffUpdated(params: unknown): LanguageModelV3StreamPart[]
    {
        const p = (params ?? {}) as TurnDiffUpdatedNotification;
        if (!p.turnId || typeof p.diff !== "string")
        {
            return [];
        }

        const parts: LanguageModelV3StreamPart[] = [];
        this.ensureStreamStarted(parts);
        const tracked = this.turnDiffByTurnId.get(p.turnId);
        const toolCallId = tracked?.toolCallId ?? `turn-diff:${p.turnId}`;
        const toolName = "codex_turn_diff";
        const item = turnDiffItemForNotification(p, toolCallId, "inProgress", this.threadCwd);

        if (!tracked)
        {
            parts.push(
                this.withMeta({
                    type: "tool-call",
                    toolCallId,
                    toolName,
                    input: JSON.stringify({ turnId: p.turnId }),
                    providerExecuted: true,
                    dynamic: true,
                }),
            );
        }

        parts.push(
            this.withMeta({
                type: "tool-result",
                toolCallId,
                toolName,
                result: asToolResult({ item }),
                preliminary: true,
            }),
        );
        this.turnDiffByTurnId.set(p.turnId, {
            toolCallId,
            cwd: this.threadCwd,
            diff: p.diff,
        });

        return parts;
    }

    // item/fileChange/patchUpdated
    private handleFileChangePatchUpdated(params: unknown): LanguageModelV3StreamPart[]
    {
        const p = (params ?? {}) as FileChangePatchUpdatedNotification;
        if (!p.turnId || !p.itemId || !Array.isArray(p.changes))
        {
            return [];
        }

        const key = turnItemKey(p.turnId, p.itemId);
        const tracked = this.fileChangePatchByItemKey.get(key);
        this.fileChangePatchByItemKey.set(key, {
            cwd: tracked?.cwd ?? this.currentCwdByTurnId.get(p.turnId) ?? this.threadCwd,
            changes: p.changes,
        });
        return [];
    }

    // item/mcpToolCall/progress
    private handleMcpToolCallProgress(params: unknown): LanguageModelV3StreamPart[]
    {
        const p = (params ?? {}) as McpToolCallProgressNotification;
        if (!p.itemId || !p.message)
        {
            return [];
        }
        const tracked = this.openToolCalls.get(p.itemId);
        if (!tracked)
        {
            return [];
        }
        // preliminary: true causes the AI SDK to replace the previous tool-result
        // with this one, so each progress message overwrites the last rather than
        // accumulating. p.message is just the current status (e.g. "Searching...").
        return [
            this.withMeta({
                type: "tool-result",
                toolCallId: p.itemId,
                toolName: tracked.toolName,
                result: asToolResult(stripUndefined({ output: p.message, item: tracked.item })),
                preliminary: true,
            }),
        ];
    }

    // item/autoApprovalReview/started
    private handleAutoApprovalReviewStarted(params: unknown): LanguageModelV3StreamPart[]
    {
        const p = (params ?? {}) as ItemGuardianApprovalReviewStartedNotification;
        if (!p.reviewId)
        {
            return [];
        }

        const parts: LanguageModelV3StreamPart[] = [];
        const item = autoApprovalReviewItem(p, "inProgress");
        this.startProviderToolCall(parts, autoApprovalReviewInvocation(item), {
            item,
            emitPreliminaryItem: true,
        });
        return parts;
    }

    // item/autoApprovalReview/completed
    private handleAutoApprovalReviewCompleted(params: unknown): LanguageModelV3StreamPart[]
    {
        const p = (params ?? {}) as ItemGuardianApprovalReviewCompletedNotification;
        if (!p.reviewId)
        {
            return [];
        }

        const parts: LanguageModelV3StreamPart[] = [];
        const item = autoApprovalReviewItem(p, "completed");
        const invocation = autoApprovalReviewInvocation(item);
        if (!this.openToolCalls.has(invocation.toolCallId))
        {
            this.startProviderToolCall(parts, invocation, { item });
        }

        this.ensureStreamStarted(parts);
        parts.push(
            this.withMeta({
                type: "tool-result",
                toolCallId: invocation.toolCallId,
                toolName: invocation.toolName,
                result: asToolResult(invocation.result),
            }),
        );
        this.openToolCalls.delete(invocation.toolCallId);
        return parts;
    }

    // item/tool/callStarted
    private handleToolCallStarted(params: unknown): LanguageModelV3StreamPart[]
    {
        const p = (params ?? {}) as { callId?: string; tool?: string };
        if (!p.callId || !p.tool)
        {
            return [];
        }
        const parts: LanguageModelV3StreamPart[] = [];
        this.ensureStreamStarted(parts);
        parts.push(
            this.withMeta({ type: "tool-input-start", id: p.callId, toolName: p.tool, dynamic: true }),
        );
        return parts;
    }

    // item/tool/callDelta
    private handleToolCallDelta(params: unknown): LanguageModelV3StreamPart[]
    {
        const p = (params ?? {}) as { callId?: string; delta?: string };
        if (!p.callId || !p.delta)
        {
            return [];
        }
        return [this.withMeta({ type: "tool-input-delta", id: p.callId, delta: p.delta })];
    }

    // item/tool/callFinished
    private handleToolCallFinished(params: unknown): LanguageModelV3StreamPart[]
    {
        const p = (params ?? {}) as { callId?: string };
        if (!p.callId)
        {
            return [];
        }
        return [this.withMeta({ type: "tool-input-end", id: p.callId })];
    }

    // item/tool/call
    private handleToolCall(params: unknown): LanguageModelV3StreamPart[]
    {
        const p = (params ?? {}) as { callId?: string; tool?: string; arguments?: unknown };
        if (!p.callId || !p.tool)
        {
            return [];
        }
        // SDK dynamic tools (dynamicToolCall items) are handled by the cross-call
        // handler in model.ts — suppress the mapper's duplicate emission.
        if (this._sdkDynamicToolCallIds.has(p.callId))
        {
            return [];
        }
        return this.startDynamicToolCall({
            id: p.callId,
            tool: p.tool,
            arguments: p.arguments ?? {},
        });
    }

    private startDynamicToolCall(
        item: Pick<DynamicToolCallItem, "id" | "tool" | "arguments">,
    ): LanguageModelV3StreamPart[]
    {
        if (!item.id || !item.tool)
        {
            return [];
        }

        if (this.openToolCalls.has(item.id))
        {
            return [];
        }

        const parts: LanguageModelV3StreamPart[] = [];
        this.startProviderToolCall(parts, {
            toolCallId: item.id,
            toolName: item.tool,
            input: item.arguments ?? {},
        });

        return parts;
    }

    private startProviderToolCall(
        parts: LanguageModelV3StreamPart[],
        itemOrInvocation: CodexRenderableThreadItem | CodexThreadItemToolStart,
        options: { item?: Record<string, unknown>; emitPreliminaryItem?: boolean } = {},
    ): void
    {
        const invocation =
            "toolCallId" in itemOrInvocation ? itemOrInvocation : toolInvocationForItem(itemOrInvocation);
        if (
            !invocation ||
      this.openToolCalls.has(invocation.toolCallId) ||
      this.completedProviderToolCallIds.has(invocation.toolCallId)
        )
        {
            return;
        }

        const item =
            options.item ?? (!("toolCallId" in itemOrInvocation) ? itemOrInvocation : undefined);
        if (this.emittedProviderToolCallIds.has(invocation.toolCallId))
        {
            this.openToolCalls.set(
                invocation.toolCallId,
                item ? { toolName: invocation.toolName, item } : { toolName: invocation.toolName },
            );
            return;
        }
        this.ensureStreamStarted(parts);
        this.openToolCalls.set(
            invocation.toolCallId,
            item ? { toolName: invocation.toolName, item } : { toolName: invocation.toolName },
        );
        parts.push(
            this.withMeta({
                type: "tool-call",
                toolCallId: invocation.toolCallId,
                toolName: invocation.toolName,
                input: stringifyToolInput(invocation.input),
                providerExecuted: true,
                dynamic: true,
            }),
        );
        this.emittedProviderToolCallIds.add(invocation.toolCallId);

        if (options.emitPreliminaryItem && item)
        {
            parts.push(
                this.withMeta({
                    type: "tool-result",
                    toolCallId: invocation.toolCallId,
                    toolName: invocation.toolName,
                    result: asToolResult({ item }),
                    preliminary: true,
                }),
            );
        }
    }

    // thread/tokenUsage/updated
    private handleTokenUsageUpdated(params: unknown): LanguageModelV3StreamPart[]
    {
        const p = (params ?? {}) as ThreadTokenUsageUpdatedNotification;
        const last = p.tokenUsage?.last;
        if (last)
        {
            this.latestUsage = {
                inputTokens: {
                    total: last.inputTokens,
                    noCache: undefined,
                    cacheRead: last.cachedInputTokens,
                    cacheWrite: undefined,
                },
                outputTokens: {
                    total: last.outputTokens,
                    text: undefined,
                    reasoning: last.reasoningOutputTokens,
                },
            };
        }
        return [];
    }

    /** Snapshots provider-executed tool calls still awaiting item/completed, for parking across a cross-call step boundary. */
    takeOpenToolCalls(): Array<{ itemId: string; toolName: string }>
    {
        return [...this.openToolCalls].map(([itemId, tracked]) => ({
            itemId,
            toolName: tracked.toolName,
        }));
    }

    /** Adopts parked open tool calls from a previous step so their late item/completed emits the real tool-result here. */
    adoptOpenToolCalls(calls: Array<{ itemId: string; toolName: string }>): void
    {
        for (const call of calls)
        {
            this.openToolCalls.set(call.itemId, { toolName: call.toolName });
        }
    }

    /** Emits synthetic error tool-results for all still-open provider-executed calls and clears them. */
    closeOpenToolCalls(reason: string): LanguageModelV3StreamPart[]
    {
        const parts: LanguageModelV3StreamPart[] = [];

        for (const [itemId, tracked] of this.openToolCalls)
        {
            parts.push(
                this.withMeta({
                    type: "tool-result",
                    toolCallId: itemId,
                    toolName: tracked.toolName,
                    result: { error: reason },
                    isError: true,
                }),
            );
            this.completedProviderToolCallIds.add(itemId);
        }
        this.openToolCalls.clear();

        return parts;
    }

    // turn/completed
    private handleTurnCompleted(params: unknown): LanguageModelV3StreamPart[]
    {
        const parts: LanguageModelV3StreamPart[] = [];
        this.ensureStreamStarted(parts);

        const completed = (params ?? {}) as TurnCompletedNotification;
        const turnDurationMs = completed.turn?.durationMs;

        for (const itemId of this.openTextParts)
        {
            parts.push(this.withMeta({ type: "text-end", id: itemId }, this.agentMessageMetadata(itemId)));
        }
        this.openTextParts.clear();
        this.agentMessagePhaseByItemId.clear();

        for (const itemId of this.openReasoningParts)
        {
            parts.push(this.withMeta({ type: "reasoning-end", id: itemId }));
        }
        this.openReasoningParts.clear();

        parts.push(...this.closeOpenToolCalls("Tool call did not complete before turn ended"));
        this._sdkDynamicToolCallIds.clear();

        if (completed.turn?.id)
        {
            const patchBatches = completed.turn.itemsView === "full"
                ? fileChangeDiffBatchesForOrderedItems(completed.turn.items, this.threadCwd)
                : this.fileChangeBatchesByTurnId.get(completed.turn.id);
            const turnDiff = this.turnDiffByTurnId.get(completed.turn.id);
            if (turnDiff)
            {
                const item = turnDiffItem({
                    id: turnDiff.toolCallId,
                    threadId: this.threadId,
                    status: "completed",
                    cwd: turnDiff.cwd,
                    diff: turnDiff.diff,
                    patchBatches,
                });
                parts.push(
                    this.withMeta({
                        type: "tool-result",
                        toolCallId: turnDiff.toolCallId,
                        toolName: "codex_turn_diff",
                        result: asToolResult({ item }),
                    }),
                );
                this.turnDiffByTurnId.delete(completed.turn.id);
            }
            this.currentCwdByTurnId.delete(completed.turn.id);
            this.fileChangeBatchesByTurnId.delete(completed.turn.id);
            for (const key of this.fileChangePatchByItemKey.keys())
            {
                if (key.startsWith(`${completed.turn.id}\0`))
                {
                    this.fileChangePatchByItemKey.delete(key);
                }
            }
            this.planSequenceByTurnId.delete(completed.turn.id);
            this.planSequenceByTurnId.delete(`diff:${completed.turn.id}`);
        }
        const usage = this.latestUsage ?? EMPTY_USAGE;
        const errorMessage = turnErrorMessage(completed.turn?.status, completed.turn?.error);
        if (errorMessage)
        {
            parts.push(this.withMeta({ type: "error", error: new Error(errorMessage) }));
        }
        parts.push(
            this.withMeta(
                { type: "finish", finishReason: toFinishReason(completed.turn?.status), usage },
                typeof turnDurationMs === "number" && Number.isFinite(turnDurationMs)
                    ? { turnDurationMs }
                    : undefined,
            ),
        );
        return parts;
    }
}
